// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.6.1
// source: ad_search/v1/ad_search.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdSearchService_CreateAd_FullMethodName       = "/ad_search.v1.AdSearchService/CreateAd"
	AdSearchService_GetAd_FullMethodName          = "/ad_search.v1.AdSearchService/GetAd"
	AdSearchService_GetUserAds_FullMethodName     = "/ad_search.v1.AdSearchService/GetUserAds"
	AdSearchService_UpdateAd_FullMethodName       = "/ad_search.v1.AdSearchService/UpdateAd"
	AdSearchService_DeleteAd_FullMethodName       = "/ad_search.v1.AdSearchService/DeleteAd"
	AdSearchService_ListAds_FullMethodName        = "/ad_search.v1.AdSearchService/ListAds"
	AdSearchService_ListCategories_FullMethodName = "/ad_search.v1.AdSearchService/ListCategories"
	AdSearchService_GetCategory_FullMethodName    = "/ad_search.v1.AdSearchService/GetCategory"
	AdSearchService_UploadMedia_FullMethodName    = "/ad_search.v1.AdSearchService/UploadMedia"
	AdSearchService_GetMedia_FullMethodName       = "/ad_search.v1.AdSearchService/GetMedia"
)

// AdSearchServiceClient is the client API for AdSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdSearchServiceClient interface {
	// Объявления
	CreateAd(ctx context.Context, in *CreateAdRequest, opts ...grpc.CallOption) (*CreateAdResponse, error)
	GetAd(ctx context.Context, in *GetAdRequest, opts ...grpc.CallOption) (*GetAdResponse, error)
	GetUserAds(ctx context.Context, in *GetUserAdsRequest, opts ...grpc.CallOption) (*GetUserAdsResponse, error)
	UpdateAd(ctx context.Context, in *UpdateAdRequest, opts ...grpc.CallOption) (*UpdateAdResponse, error)
	DeleteAd(ctx context.Context, in *DeleteAdRequest, opts ...grpc.CallOption) (*DeleteAdResponse, error)
	ListAds(ctx context.Context, in *ListAdsRequest, opts ...grpc.CallOption) (*ListAdsResponse, error)
	// Категории
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
	GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error)
	// Медиа
	UploadMedia(ctx context.Context, in *UploadMediaRequest, opts ...grpc.CallOption) (*UploadMediaResponse, error)
	GetMedia(ctx context.Context, in *GetMediaRequest, opts ...grpc.CallOption) (*GetMediaResponse, error)
}

type adSearchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdSearchServiceClient(cc grpc.ClientConnInterface) AdSearchServiceClient {
	return &adSearchServiceClient{cc}
}

func (c *adSearchServiceClient) CreateAd(ctx context.Context, in *CreateAdRequest, opts ...grpc.CallOption) (*CreateAdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAdResponse)
	err := c.cc.Invoke(ctx, AdSearchService_CreateAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adSearchServiceClient) GetAd(ctx context.Context, in *GetAdRequest, opts ...grpc.CallOption) (*GetAdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdResponse)
	err := c.cc.Invoke(ctx, AdSearchService_GetAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adSearchServiceClient) GetUserAds(ctx context.Context, in *GetUserAdsRequest, opts ...grpc.CallOption) (*GetUserAdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAdsResponse)
	err := c.cc.Invoke(ctx, AdSearchService_GetUserAds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adSearchServiceClient) UpdateAd(ctx context.Context, in *UpdateAdRequest, opts ...grpc.CallOption) (*UpdateAdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAdResponse)
	err := c.cc.Invoke(ctx, AdSearchService_UpdateAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adSearchServiceClient) DeleteAd(ctx context.Context, in *DeleteAdRequest, opts ...grpc.CallOption) (*DeleteAdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAdResponse)
	err := c.cc.Invoke(ctx, AdSearchService_DeleteAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adSearchServiceClient) ListAds(ctx context.Context, in *ListAdsRequest, opts ...grpc.CallOption) (*ListAdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdsResponse)
	err := c.cc.Invoke(ctx, AdSearchService_ListAds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adSearchServiceClient) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCategoriesResponse)
	err := c.cc.Invoke(ctx, AdSearchService_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adSearchServiceClient) GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryResponse)
	err := c.cc.Invoke(ctx, AdSearchService_GetCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adSearchServiceClient) UploadMedia(ctx context.Context, in *UploadMediaRequest, opts ...grpc.CallOption) (*UploadMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadMediaResponse)
	err := c.cc.Invoke(ctx, AdSearchService_UploadMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adSearchServiceClient) GetMedia(ctx context.Context, in *GetMediaRequest, opts ...grpc.CallOption) (*GetMediaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMediaResponse)
	err := c.cc.Invoke(ctx, AdSearchService_GetMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdSearchServiceServer is the server API for AdSearchService service.
// All implementations must embed UnimplementedAdSearchServiceServer
// for forward compatibility.
type AdSearchServiceServer interface {
	// Объявления
	CreateAd(context.Context, *CreateAdRequest) (*CreateAdResponse, error)
	GetAd(context.Context, *GetAdRequest) (*GetAdResponse, error)
	GetUserAds(context.Context, *GetUserAdsRequest) (*GetUserAdsResponse, error)
	UpdateAd(context.Context, *UpdateAdRequest) (*UpdateAdResponse, error)
	DeleteAd(context.Context, *DeleteAdRequest) (*DeleteAdResponse, error)
	ListAds(context.Context, *ListAdsRequest) (*ListAdsResponse, error)
	// Категории
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error)
	GetCategory(context.Context, *GetCategoryRequest) (*GetCategoryResponse, error)
	// Медиа
	UploadMedia(context.Context, *UploadMediaRequest) (*UploadMediaResponse, error)
	GetMedia(context.Context, *GetMediaRequest) (*GetMediaResponse, error)
	mustEmbedUnimplementedAdSearchServiceServer()
}

// UnimplementedAdSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdSearchServiceServer struct{}

func (UnimplementedAdSearchServiceServer) CreateAd(context.Context, *CreateAdRequest) (*CreateAdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAd not implemented")
}
func (UnimplementedAdSearchServiceServer) GetAd(context.Context, *GetAdRequest) (*GetAdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAd not implemented")
}
func (UnimplementedAdSearchServiceServer) GetUserAds(context.Context, *GetUserAdsRequest) (*GetUserAdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserAds not implemented")
}
func (UnimplementedAdSearchServiceServer) UpdateAd(context.Context, *UpdateAdRequest) (*UpdateAdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAd not implemented")
}
func (UnimplementedAdSearchServiceServer) DeleteAd(context.Context, *DeleteAdRequest) (*DeleteAdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAd not implemented")
}
func (UnimplementedAdSearchServiceServer) ListAds(context.Context, *ListAdsRequest) (*ListAdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAds not implemented")
}
func (UnimplementedAdSearchServiceServer) ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedAdSearchServiceServer) GetCategory(context.Context, *GetCategoryRequest) (*GetCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategory not implemented")
}
func (UnimplementedAdSearchServiceServer) UploadMedia(context.Context, *UploadMediaRequest) (*UploadMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadMedia not implemented")
}
func (UnimplementedAdSearchServiceServer) GetMedia(context.Context, *GetMediaRequest) (*GetMediaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMedia not implemented")
}
func (UnimplementedAdSearchServiceServer) mustEmbedUnimplementedAdSearchServiceServer() {}
func (UnimplementedAdSearchServiceServer) testEmbeddedByValue()                         {}

// UnsafeAdSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdSearchServiceServer will
// result in compilation errors.
type UnsafeAdSearchServiceServer interface {
	mustEmbedUnimplementedAdSearchServiceServer()
}

func RegisterAdSearchServiceServer(s grpc.ServiceRegistrar, srv AdSearchServiceServer) {
	// If the following call panics, it indicates UnimplementedAdSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdSearchService_ServiceDesc, srv)
}

func _AdSearchService_CreateAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdSearchServiceServer).CreateAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdSearchService_CreateAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdSearchServiceServer).CreateAd(ctx, req.(*CreateAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdSearchService_GetAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdSearchServiceServer).GetAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdSearchService_GetAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdSearchServiceServer).GetAd(ctx, req.(*GetAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdSearchService_GetUserAds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdSearchServiceServer).GetUserAds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdSearchService_GetUserAds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdSearchServiceServer).GetUserAds(ctx, req.(*GetUserAdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdSearchService_UpdateAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdSearchServiceServer).UpdateAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdSearchService_UpdateAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdSearchServiceServer).UpdateAd(ctx, req.(*UpdateAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdSearchService_DeleteAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdSearchServiceServer).DeleteAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdSearchService_DeleteAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdSearchServiceServer).DeleteAd(ctx, req.(*DeleteAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdSearchService_ListAds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdSearchServiceServer).ListAds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdSearchService_ListAds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdSearchServiceServer).ListAds(ctx, req.(*ListAdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdSearchService_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdSearchServiceServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdSearchService_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdSearchServiceServer).ListCategories(ctx, req.(*ListCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdSearchService_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdSearchServiceServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdSearchService_GetCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdSearchServiceServer).GetCategory(ctx, req.(*GetCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdSearchService_UploadMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdSearchServiceServer).UploadMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdSearchService_UploadMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdSearchServiceServer).UploadMedia(ctx, req.(*UploadMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdSearchService_GetMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdSearchServiceServer).GetMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdSearchService_GetMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdSearchServiceServer).GetMedia(ctx, req.(*GetMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdSearchService_ServiceDesc is the grpc.ServiceDesc for AdSearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdSearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ad_search.v1.AdSearchService",
	HandlerType: (*AdSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAd",
			Handler:    _AdSearchService_CreateAd_Handler,
		},
		{
			MethodName: "GetAd",
			Handler:    _AdSearchService_GetAd_Handler,
		},
		{
			MethodName: "GetUserAds",
			Handler:    _AdSearchService_GetUserAds_Handler,
		},
		{
			MethodName: "UpdateAd",
			Handler:    _AdSearchService_UpdateAd_Handler,
		},
		{
			MethodName: "DeleteAd",
			Handler:    _AdSearchService_DeleteAd_Handler,
		},
		{
			MethodName: "ListAds",
			Handler:    _AdSearchService_ListAds_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _AdSearchService_ListCategories_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _AdSearchService_GetCategory_Handler,
		},
		{
			MethodName: "UploadMedia",
			Handler:    _AdSearchService_UploadMedia_Handler,
		},
		{
			MethodName: "GetMedia",
			Handler:    _AdSearchService_GetMedia_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ad_search/v1/ad_search.proto",
}
